@startuml

:Secretaria: as secretaria
:Aluno: as aluno
:Professor: as professor 
:Sistema Financeiro: as sistemaFinanceiro
:Usuario: as usuario

"Gerar currículo semestral" as (gerarCurriculo)
"Persistir informações" as (persistirInformacoes)
"Matricular em disciplina" as (matricularDisciplina)
"Cancelar matricula em disciplina" as (cancelarMatricula)
"Abrir matriculas" as (abrirMatriculas)
"Encerrar matrículas" as (encerrarMatriculas)
"Cancelar disciplina" as (cancelarDisciplina)
"Notificar matrícula de aluno" as (notificarMatricula)
"Verificar validade da disciplina" as (verificarValidadeDisciplina)
"Verificar alunos em disciplina" as (verificarAlunosDisciplina) 
"Login" as (login)
"Cadastrar credenciais" as (cadastrarCredenciais)
"Validar senha" as (validarSenha)

secretaria --> gerarCurriculo
secretaria --> persistirInformacoes
aluno --> matricularDisciplina
matricularDisciplina --> notificarMatricula
aluno --> cancelarMatricula
secretaria --> abrirMatriculas
secretaria --> verificarValidadeDisciplina 
verificarValidadeDisciplina ..> encerrarMatriculas : <<extends>>
verificarValidadeDisciplina ..> cancelarDisciplina : <<extends>>
notificarMatricula --> sistemaFinanceiro
professor --> verificarAlunosDisciplina
usuario --> login
login ..> validarSenha : <<includes>>
usuario --> cadastrarCredenciais


usuario <|-- secretaria
usuario <|-- aluno
usuario <|-- professor

@enduml